import { Internship } from './types';

// This file is no longer used for the primary internship list, 
// as it is now dynamically generated by the Gemini API.
// It can be kept for testing or fallback purposes if needed.
export const INTERNSHIPS_DATA: Internship[] = [];
